# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'laser.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QDialog, QDoubleSpinBox,
    QFrame, QLabel, QLineEdit, QSizePolicy,
    QSlider, QToolButton, QWidget)
import main_rc

class Ui_dialogLaserControl(object):
    def setupUi(self, dialogLaserControl):
        if not dialogLaserControl.objectName():
            dialogLaserControl.setObjectName(u"dialogLaserControl")
        dialogLaserControl.resize(240, 407)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogLaserControl.sizePolicy().hasHeightForWidth())
        dialogLaserControl.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        dialogLaserControl.setWindowIcon(icon)
        dialogLaserControl.setStyleSheet(u"font: 11pt \"Segoe UI\";")
        self.imgLaser = QLabel(dialogLaserControl)
        self.imgLaser.setObjectName(u"imgLaser")
        self.imgLaser.setGeometry(QRect(11, 50, 100, 100))
        self.imgLaser.setStyleSheet(u"image: url(:/main/laser.svg);")
        self.imgLaser.setFrameShape(QFrame.Shape.NoFrame)
        self.label = QLabel(dialogLaserControl)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 200, 91, 20))
        self.label.setStyleSheet(u"")
        self.label.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.btnClose = QToolButton(dialogLaserControl)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(170, 370, 63, 31))
        self.btnClose.setIconSize(QSize(61, 31))
        self.btnOn = QToolButton(dialogLaserControl)
        self.btnOn.setObjectName(u"btnOn")
        self.btnOn.setGeometry(QRect(170, 240, 63, 31))
        self.btnOn.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/laser/laserform_on_disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon1.addFile(u":/laser/laserform_on_disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        icon1.addFile(u":/laser/laserform_on.png", QSize(), QIcon.Mode.Active, QIcon.State.Off)
        icon1.addFile(u":/laser/laserform_off.png", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.btnOn.setIcon(icon1)
        self.btnOn.setIconSize(QSize(61, 31))
        self.btnOn.setCheckable(True)
        self.btnOn.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.sliderEnable = QSlider(dialogLaserControl)
        self.sliderEnable.setObjectName(u"sliderEnable")
        self.sliderEnable.setGeometry(QRect(140, 110, 22, 71))
        self.sliderEnable.setStyleSheet(u"")
        self.sliderEnable.setMaximum(2)
        self.sliderEnable.setSingleStep(1)
        self.sliderEnable.setPageStep(1)
        self.sliderEnable.setOrientation(Qt.Orientation.Vertical)
        self.sliderEnable.setInvertedAppearance(True)
        self.sliderEnable.setTickPosition(QSlider.TickPosition.NoTicks)
        self.sliderEnable.setTickInterval(10)
        self.label_2 = QLabel(dialogLaserControl)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(170, 110, 61, 16))
        self.label_3 = QLabel(dialogLaserControl)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(170, 160, 61, 16))
        self.lblStatus = QLabel(dialogLaserControl)
        self.lblStatus.setObjectName(u"lblStatus")
        self.lblStatus.setGeometry(QRect(140, 30, 101, 41))
        self.lblStatus.setStyleSheet(u"")
        self.lblStatus.setFrameShape(QFrame.Shape.NoFrame)
        self.lblStatus.setFrameShadow(QFrame.Shadow.Plain)
        self.lblStatus.setTextFormat(Qt.TextFormat.PlainText)
        self.lblStatus.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lblStatus.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.sliderLaser = QDoubleSpinBox(dialogLaserControl)
        self.sliderLaser.setObjectName(u"sliderLaser")
        self.sliderLaser.setGeometry(QRect(130, 190, 101, 41))
        self.sliderLaser.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.sliderLaser.setFrame(True)
        self.sliderLaser.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.sliderLaser.setDecimals(1)
        self.txtPyroIntercept = QLineEdit(dialogLaserControl)
        self.txtPyroIntercept.setObjectName(u"txtPyroIntercept")
        self.txtPyroIntercept.setGeometry(QRect(120, 313, 113, 21))
        self.txtPyroIntercept.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.txtPyroSlope = QLineEdit(dialogLaserControl)
        self.txtPyroSlope.setObjectName(u"txtPyroSlope")
        self.txtPyroSlope.setGeometry(QRect(120, 340, 113, 21))
        self.txtPyroSlope.setStyleSheet(u"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255)")
        self.line = QFrame(dialogLaserControl)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(5, 273, 230, 3))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_4 = QLabel(dialogLaserControl)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 310, 81, 20))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_5 = QLabel(dialogLaserControl)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 340, 81, 20))
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_6 = QLabel(dialogLaserControl)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 111, 20))
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.label_7 = QLabel(dialogLaserControl)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 280, 211, 20))
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.btnSave = QToolButton(dialogLaserControl)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(100, 370, 63, 31))
        self.btnSave.setIconSize(QSize(61, 31))
        self.label.raise_()
        self.btnClose.raise_()
        self.btnOn.raise_()
        self.sliderEnable.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.imgLaser.raise_()
        self.lblStatus.raise_()
        self.sliderLaser.raise_()
        self.txtPyroIntercept.raise_()
        self.txtPyroSlope.raise_()
        self.line.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.btnSave.raise_()

        self.retranslateUi(dialogLaserControl)

        QMetaObject.connectSlotsByName(dialogLaserControl)
    # setupUi

    def retranslateUi(self, dialogLaserControl):
        dialogLaserControl.setWindowTitle(QCoreApplication.translate("dialogLaserControl", u"Laser Manual Control", None))
        self.imgLaser.setText("")
        self.label.setText(QCoreApplication.translate("dialogLaserControl", u"Laser Power", None))
        self.btnClose.setText(QCoreApplication.translate("dialogLaserControl", u"Close", None))
        self.btnOn.setText("")
        self.label_2.setText(QCoreApplication.translate("dialogLaserControl", u"Disabled", None))
        self.label_3.setText(QCoreApplication.translate("dialogLaserControl", u"Enabled", None))
        self.lblStatus.setText("")
        self.txtPyroIntercept.setText(QCoreApplication.translate("dialogLaserControl", u"0.0", None))
        self.txtPyroSlope.setText(QCoreApplication.translate("dialogLaserControl", u"0.0", None))
        self.label_4.setText(QCoreApplication.translate("dialogLaserControl", u"Intercept", None))
        self.label_5.setText(QCoreApplication.translate("dialogLaserControl", u"Slope", None))
        self.label_6.setText(QCoreApplication.translate("dialogLaserControl", u"Laser Control", None))
        self.label_7.setText(QCoreApplication.translate("dialogLaserControl", u"Pyrometer Calibration", None))
        self.btnSave.setText(QCoreApplication.translate("dialogLaserControl", u"Save", None))
    # retranslateUi

